<a href="https://colab.research.google.com/github/SretenGlavinceski/Linear_Algebra_2024/blob/master/lab0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Лабораториска вежба 0**

### Задача 1.
Со помош на `list comprehension` да се дефинираат следните `python` листи (без `numpy`):  
1. Листа од сите непарни природни броеви помали од 30.
2. Листа од сите прости природни броеви (броеви кои се делат само со себе и 1) помали од 100.
3. Матрица (листа од листи) со големина $3 \times 4$ каде елементот $m_{i, ~j}$ во редот $i$ и колоната $j$ ја прима вредноста $i \cdot j$.

In [5]:
# 1.
odds = [num for num in range(30) if num % 2 != 0]
print(odds)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]


In [7]:
# 2.

def is_prime(number):
    return not any([number % i == 0 for i in range(2, number)])

primes = [num for num in range(100) if is_prime(num)]
print(primes)

[0, 1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [10]:
# 3.

matrix = [[i * j for i in range(3)] for j in range(4)]
_ = [print(row) for row in matrix]

[0, 0, 0]
[0, 1, 2]
[0, 2, 4]
[0, 3, 6]


### Задача 2.
Со помош на `numpy` низи да се пресметаат следните изрази  
1. $$2 \cdot A \circ B$$  
каде $A = \begin{pmatrix}1 \\ 3 \\ 4 \\ 7\end{pmatrix}$ и $B = \begin{pmatrix}5 \\ 2 \\ 1 \\ 2\end{pmatrix}$.  
2. $$(M - N) \circ T$$  
каде $M = \begin{pmatrix}1 & 10 & 4 \\ 3 & 4 & 0\end{pmatrix}$, $N = \begin{pmatrix}0 & 2 & 2\\ 7 & 1 & 5\end{pmatrix}$ и $T = \begin{pmatrix}\frac12 & 1 & 0 \\ 0 & 1 & \frac14\end{pmatrix}$.  
3. $$\frac{1}{n+1} H_n \circ I_n$$
каде $H_n = \begin{pmatrix}1 & 2 & 4 & \cdots & 2^{n-1} \\ 2 & 4 & 8 & \cdots & 2^n \\ \vdots & \vdots & \vdots & \ddots & \vdots \\ 2^{n-1} & 2^n & 2^{n+1} & \cdots & 2^{2n-2}\end{pmatrix}$ и $I_n \begin{pmatrix}1 & 0 & 0 & \cdots & 0 \\ 0 & 1 & 0 & \cdots & 0 \\ \vdots & \vdots &  \vdots & \ddots & \vdots \\ 0 & 0 & 0 & \cdots & 1\end{pmatrix}$ т.е. е единечната квадратна матрица од ред $n$.

Сите операции се дефинирани елемент-по-елемент.   
За 2.3. може да се дефинира функција со влезен параметар $n$ која ќе ја генерира соодветната матрица пресметана од дадениот израз.

In [13]:
# 1.
import numpy as np

matrix_1 = np.array([[1, 3, 4, 7]])
matrix_2 = np.array([[5, 2, 1, 2]])

result = 2 * matrix_1 * matrix_2

print(result)

[[10 12  8 28]]


In [15]:
# 2.
import numpy as np

matrix_M = np.array([[1, 10, 4], [3, 4, 0]])
matrix_N = np.array([[0, 2, 2], [7, 1, 5]])
matrix_T = np.array([[0.5, 1, 0], [0, 1, 0.25]])

result = (matrix_M - matrix_N) * matrix_T

print(result)

[[ 0.5   8.    0.  ]
 [-0.    3.   -1.25]]


In [18]:
# 3.
import numpy as np

def create_Hn_matrix(n):
  return np.array([[pow(2, i + j) for i in range(n)] for j in range(n)])


n = int(input("Enter value for n: "))

matrix_Hn = create_Hn_matrix(n)
matrix_In = np.eye(n)

print(matrix_Hn, "\n")
print(matrix_In, "\n")

result = (1 / (n + 1)) * matrix_Hn * matrix_In
print(result)

Enter value for n: 4
[[ 1  2  4  8]
 [ 2  4  8 16]
 [ 4  8 16 32]
 [ 8 16 32 64]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[[ 0.2  0.   0.   0. ]
 [ 0.   0.8  0.   0. ]
 [ 0.   0.   3.2  0. ]
 [ 0.   0.   0.  12.8]]


### Задача 3.
---

Дефинирај класа `Array` која ќе чува `numpy` низа од случајни вредности. Класата треба да содржи **конструктор** со параметар `shape` која ќе биде листа од димензиите на низата. Конструкторот треба да ја иницијализира низата со случајни вредности на интервалот \(0, 5\].

Класата содржи функција членка **compare_array** која како аргумент прима објект од класата `Array`.  
Функцијата враќа *boolean*, и тоа *False* ако низите имаат различни димензии односно *shape* параметри.  
Во случај низите да имаат исти димензии, се споредува елемент-по-елемент дали елементите во `self` објектот се во просечен случај поголеми од елементите во објектот примен како аргумент.
Се враќа *True* ако `self` има повеќе поголеми елементи, инаку се враќа вредноста `False`.

In [30]:
import numpy as np

class Array:
  def __init__(self, shape):
    self.np_array = 5 * np.random.random(shape)

  def compare_array(self, arr_object):
    if self.np_array.shape == arr_object.np_array.shape:
      count = sum(1 for i, j in zip(self.np_array.flatten(), arr_object.np_array.flatten()) if i > j)
      return count >= self.np_array.size / 2
    return False


array_1 = Array([2, 4])
array_2 = Array([2, 4])

print(array_1.np_array, "\n")
print(array_2.np_array, "\n")

print(array_1.compare_array(array_2))

[[4.31861359 4.87729768 0.38859496 2.31455926]
 [1.37761729 3.60567929 3.12021806 3.42683789]] 

[[3.74047925 2.77251185 2.30881696 0.08672625]
 [2.31480784 2.00524633 4.09368954 4.32054724]] 

True
